version: '{build}'
image: Visual Studio 2017
environment:
  CONFIG_TYPE: Release
  matrix:
  - BUILD_TYPE: Visual Studio 15 2017 Win64
    BUILD_PLAY: ON
    INSTALLER_SCRIPT: installer64.nsi
    QT_FLAVOR: msvc2017_64

build_script:
- cmd: >-
    set REPO_COMMIT_SHORT=%APPVEYOR_REPO_COMMIT:~0,8%
    
    appveyor SetVariable -Name REPO_COMMIT_SHORT -Value %REPO_COMMIT_SHORT%
    
    git submodule update -q --init --recursive
    
    call appveyor_build.cmd
    
artifacts:
- path: $(REPO_COMMIT_SHORT)\*.exe
  name: Binaries